### ISSUE TITLE
Why a separated lib ?

### ISSUE THREAD

**Issue by damoebius** [kevinresol/tink_http_middleware#4]
Hi,
I just want to know why tink_http middleware are used from a separated haxe library ?

tink_http already has a kinb of dependency from this lib
https://github.com/haxetink/tink_http/blob/e03cd965991d3d0ec757bd005085e0c43108e0a7/src/tink/http/Handler.hx#L13

**Comment by back2dos** [comment]
Hmm, mostly it's because I've consider middlewares a relatively bad abstraction for static languages and I largely still hold that opinion. Ultimately, I'm inclined to think that for tink_web, this would be the most appropriate solution:

```haxe
class Root {
  @:sub("static") var files = new Static('./www');//looks up static files from FS
  @:sub("assets") var assets = Assets.from('./assets');//bakes assets into output and serves them from there
}
```

Another issue is that for example the static middleware depends on a file system abstraction, which makes no sense for client side tink_http.

All that said, if you guys feel strongly for putting these two together, I won't be opposed.

**Comment by kevinresol** [comment]
Yeah I don't want bring in the additional dependencies.
